# Generated by Django 5.2.2 on 2025-09-10 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('include_uppercase', models.BooleanField(default=True)),
                ('include_lowercase', models.BooleanField(default=True)),
                ('include_numbers', models.BooleanField(default=True)),
                ('include_symbols', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
